import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :devtest_elixir, PrivateAPI.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  cache_static_manifest: "priv/static/cache_manifest.json",
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  secret_key_base: "OJnXxkR6BdPncB5j/LKT6HCCj+Meh/ylNuEaxRnPtJBV0xZJAhiMu9/luvgZ8xpD/",
  server: true

config :devtest_elixir, PublicAPI.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  cache_static_manifest: "priv/static/cache_manifest.json",
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  secret_key_base: "V6xlaIK77mj430HkskijK3juoD6bmhhOHFkHVyT9onyUh2nmP9OuziZqg597GHU",
  server: true

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: DevtestElixir.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
